// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY IT.

import { Asset, Entry } from "contentful";

export interface ICoachFields {
  /** Title */
  title: string;

  /** Slug */
  slug?: string | undefined;

  /** Category */
  category: "Head" | "Main" | "Guest";

  /** Image */
  image: Asset;

  /** Bio */
  bio?: string | undefined;

  /** Spotify URL */
  spotifyUrl?: string | undefined;

  /** Labels */
  labels?: Record<string, any> | undefined;

  /** Socials */
  socials?: Record<string, any> | undefined;
}

export interface ICoach extends Entry<ICoachFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "coach";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface ICoachesCopyFields {
  /** Header */
  header: string;

  /** Paragraph */
  paragraph: string;
}

export interface ICoachesCopy extends Entry<ICoachesCopyFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "coachesCopy";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface ICommunityCopyFields {
  /** Intro Header */
  introHeader: string;

  /** Intro Paragraph */
  introParagraph: string;

  /** Services Header */
  servicesHeader: string;

  /** Service One Description */
  serviceOneDescription: string;

  /** Service Two Header */
  serviceTwoHeader: string;

  /** Service Two Description */
  serviceTwoDescription: string;

  /** Service Three Header */
  serviceThreeHeader: string;

  /** Service Three Description */
  serviceThreeDescription: string;

  /** Service Four Header */
  serviceFourHeader: string;

  /** Service Four Description */
  serviceFourDescription: string;

  /** Extra One Header */
  extraOneHeader: string;

  /** Extra One Body */
  extraOneBody: string;

  /** Extra Two Header */
  extraTwoHeader: string;

  /** Extra Two Body */
  extraTwoBody: string;

  /** Extra Three Header */
  extraThreeHeader: string;

  /** Extra Three Body */
  extraThreeBody: string;

  /** About Header */
  aboutHeader: string;

  /** About Description */
  aboutDescription: string;
}

export interface ICommunityCopy extends Entry<ICommunityCopyFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "communityCopy";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IFaqFields {
  /** Question */
  question: string;

  /** Answer */
  answer: string;
}

export interface IFaq extends Entry<IFaqFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "faq";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IFeatureFields {
  /** Title */
  title: string;

  /** Package */
  package: IPackage[];
}

export interface IFeature extends Entry<IFeatureFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "feature";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IHomeCopyFields {
  /** Hero Description */
  heroDescription: string;

  /** Services Header */
  servicesHeader: string;

  /** Service One Header */
  serviceOneHeader: string;

  /** Service One Description */
  serviceOneDescription: string;

  /** Service Two Header */
  serviceTwoHeader: string;

  /** Service Two Description */
  serviceTwoDescription: string;

  /** Service Three Header */
  serviceThreeHeader: string;

  /** Service Three Description */
  serviceThreeDescription: string;

  /** Service Four Header */
  serviceFourHeader: string;

  /** Service Four Description */
  serviceFourDescription: string;

  /** Coaches Header */
  coachesHeader: string;

  /** Coaches Paragraph Header */
  coachesParagraphHeader: string;

  /** Coaches Paragraph Body */
  coachesParagraphBody: string;

  /** Testimonials Headers */
  testimonialsHeaders: string;

  /** Shop Header */
  shopHeader: string;

  /** Email Listing Header */
  emailListingHeader: string;

  /** Email Listing Description */
  emailListingDescription: string;
}

export interface IHomeCopy extends Entry<IHomeCopyFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "homeCopy";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IPackageFields {
  /** Title */
  title: string;

  /** Price */
  price: number;

  /** Link */
  link: string;

  /** Description */
  description: string;

  /** Color */
  color: string;

  /** Extras */
  extras: string;
}

export interface IPackage extends Entry<IPackageFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "package";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IShopifyCollectionFields {
  /** Access Token */
  accessToken: string;

  /** API Version */
  apiVersion: string;

  /** ShopId */
  shopId: string;

  /** Collection Name */
  collectionName: string;
}

export interface IShopifyCollection extends Entry<IShopifyCollectionFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "shopifyCollection";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface ITestimonialFields {
  /** Review */
  review: string;

  /** Author */
  author: string;

  /** Joined */
  joined: string;

  /** Image */
  image?: Asset | undefined;

  /** Approved */
  approved: boolean;
}

export interface ITestimonial extends Entry<ITestimonialFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "testimonial";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface ITutorialFields {
  /** Title */
  title: string;

  /** Video */
  video: Asset;

  /** Coach */
  coach: ICoach;
}

export interface ITutorial extends Entry<ITutorialFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "tutorial";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface ITutorialsCopyFields {
  /** Paragraph */
  paragraph: string;
}

export interface ITutorialsCopy extends Entry<ITutorialsCopyFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "tutorialsCopy";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export type CONTENT_TYPE =
  | "coach"
  | "coachesCopy"
  | "communityCopy"
  | "faq"
  | "feature"
  | "homeCopy"
  | "package"
  | "shopifyCollection"
  | "testimonial"
  | "tutorial"
  | "tutorialsCopy";

export type IEntry =
  | ICoach
  | ICoachesCopy
  | ICommunityCopy
  | IFaq
  | IFeature
  | IHomeCopy
  | IPackage
  | IShopifyCollection
  | ITestimonial
  | ITutorial
  | ITutorialsCopy;

export type LOCALE_CODE = "en-US";

export type CONTENTFUL_DEFAULT_LOCALE_CODE = "en-US";
