// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY IT.

import { Asset, Entry } from "contentful";

export interface ICoachFields {
  /** Title */
  title: string;

  /** Slug */
  slug?: string | undefined;

  /** Category */
  category: "Head" | "Main" | "Guest";

  /** Image */
  image: Asset;

  /** Bio */
  bio?: string | undefined;

  /** Spotify URL */
  spotifyUrl?: string | undefined;

  /** Labels */
  labels?: Record<string, any> | undefined;

  /** Socials */
  socials?: Record<string, any> | undefined;
}

export interface ICoach extends Entry<ICoachFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "coach";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface ICoachesCopyFields {
  /** Header */
  header: string;

  /** Paragraph */
  paragraph: string;
}

export interface ICoachesCopy extends Entry<ICoachesCopyFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "coachesCopy";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IFaqFields {
  /** Question */
  question: string;

  /** Answer */
  answer: string;
}

export interface IFaq extends Entry<IFaqFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "faq";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IFeatureFields {
  /** Title */
  title: string;

  /** Order */
  order: number;
}

export interface IFeature extends Entry<IFeatureFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "feature";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IHomeCopyFields {
  /** Home Copy */
  homeCopy?: string | undefined;

  /** Hero Description One */
  heroDescriptionOne: string;

  /** Hero Description Two */
  heroDescriptionTwo: string;

  /** Coaches Header */
  coachesHeader: string;

  /** Coaches Paragraph Header One */
  coachesParagraphHeaderOne: string;

  /** Coaches Paragraph Body One */
  coachesParagraphBodyOne: string;

  /** Testimonials Headers */
  testimonialsHeaders: string;

  /** Shop Header */
  shopHeader: string;

  /** Email Listing Header */
  emailListingHeader: string;

  /** Email Listing Description */
  emailListingDescription: string;
}

export interface IHomeCopy extends Entry<IHomeCopyFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "homeCopy";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IPackageFields {
  /** Title */
  title: string;

  /** Price */
  price: number;

  /** Link */
  link: string;

  /** Description */
  description: string;

  /** Color */
  color: string;

  /** Extras */
  extras: string;

  /** Features */
  features: IFeature[];
}

export interface IPackage extends Entry<IPackageFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "package";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IServiceFields {
  /** Title */
  title: string;

  /** Description */
  description: string;

  /** Color */
  color: string;

  /** Video */
  video?: Asset | undefined;

  /** Details (List) */
  detailsList?: string[] | undefined;

  /** Order */
  order: number;

  /** Sticker */
  sticker: Asset;
}

export interface IService extends Entry<IServiceFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "service";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IShopifyCollectionFields {
  /** Access Token */
  accessToken: string;

  /** API Version */
  apiVersion: string;

  /** ShopId */
  shopId: string;

  /** Collection Name */
  collectionName: string;
}

export interface IShopifyCollection extends Entry<IShopifyCollectionFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "shopifyCollection";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface ITeamMemberFields {
  /** Title */
  title: string;

  /** Role */
  role: string;

  /** Image */
  image: Asset;
}

export interface ITeamMember extends Entry<ITeamMemberFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "teamMember";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface ITestimonialFields {
  /** Review */
  review: string;

  /** Author */
  author: string;

  /** Joined */
  joined: string;

  /** Image */
  image?: Asset | undefined;

  /** Approved */
  approved: boolean;

  /** Rating */
  rating: number;
}

export interface ITestimonial extends Entry<ITestimonialFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "testimonial";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface ITutorialFields {
  /** Title */
  title: string;

  /** Video */
  video: Asset;

  /** Coach */
  coach: ICoach;
}

export interface ITutorial extends Entry<ITutorialFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "tutorial";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface ITutorialsCopyFields {
  /** Paragraph */
  paragraph: string;
}

export interface ITutorialsCopy extends Entry<ITutorialsCopyFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "tutorialsCopy";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export type CONTENT_TYPE =
  | "coach"
  | "coachesCopy"
  | "faq"
  | "feature"
  | "homeCopy"
  | "package"
  | "service"
  | "shopifyCollection"
  | "teamMember"
  | "testimonial"
  | "tutorial"
  | "tutorialsCopy";

export type IEntry =
  | ICoach
  | ICoachesCopy
  | IFaq
  | IFeature
  | IHomeCopy
  | IPackage
  | IService
  | IShopifyCollection
  | ITeamMember
  | ITestimonial
  | ITutorial
  | ITutorialsCopy;

export type LOCALE_CODE = "en-US";

export type CONTENTFUL_DEFAULT_LOCALE_CODE = "en-US";
